name: khalti_example
description: A new Flutter project.
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  khalti: ^1.0.2
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.1
