name: khalti_core_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  khalti_core: ^1.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.4